#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { Client } from 'pg';
import dotenv from 'dotenv';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, '..');

dotenv.config({ path: path.join(repoRoot, '.env') });
dotenv.config({ path: path.join(repoRoot, '..', '.env') });

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) {
  throw new Error('DATABASE_URL is missing. Set it in the local .env file before running backup.');
}

function resolveBackupDir() {
  const envDir = process.env.BACKUP_DIR;
  if (envDir) return envDir;

  const exactPath = 'C:\\Users\\HCS122\\OneDrive\\Documents\\Default Project\\hanycard\\backups';
  if (fs.existsSync(exactPath) || !fs.existsSync('C:\\Users\\HCS122\\OneDrive - شخصي\\hanycard\\backups')) {
    return exactPath;
  }

  const candidates = [
    exactPath,
    'C:\\Users\\HCS122\\OneDrive - شخصي\\hanycard\\backups',
    path.join(os.homedir(), 'OneDrive', 'Documents', 'Default Project', 'hanycard', 'backups'),
    path.join(os.homedir(), 'OneDrive', 'المستندات', 'Default Project', 'hanycard', 'backups'),
    path.join(os.homedir(), 'Documents', 'Default Project', 'hanycard', 'backups'),
    path.join(os.homedir(), 'OneDrive', 'Documents', 'hanycard', 'backups'),
  ];

  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) return candidate;
  }

  return exactPath;
}

const backupDir = resolveBackupDir();
console.log(`Resolved backup directory: ${backupDir}`);

function escapedSql(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (value instanceof Date) return `'${value.toISOString().replace(/'/g, "''")}'`;
  if (Buffer.isBuffer(value) || ArrayBuffer.isView(value)) {
    const bytes = Buffer.isBuffer(value)
      ? value
      : Buffer.from(value.buffer, value.byteOffset, value.byteLength);
    return `'\\x${bytes.toString('hex')}'`;
  }
  if (Array.isArray(value) || typeof value === 'object') {
    return `'${JSON.stringify(value).replace(/'/g, "''")}'`;
  }
  const text = String(value).replace(/'/g, "''");
  return `'${text}'`;
}

function formatStamp(date) {
  const pad = (n) => String(n).padStart(2, '0');
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}_${pad(date.getHours())}${pad(date.getMinutes())}${pad(date.getSeconds())}`;
}

async function main() {
  fs.mkdirSync(backupDir, { recursive: true });
  console.log(`Backup directory: ${backupDir}`);

  const client = new Client({
    connectionString: databaseUrl,
    ssl: { rejectUnauthorized: false },
  });

  try {
    await client.connect();

    const tablesResult = await client.query(`
      SELECT table_name
      FROM information_schema.tables
      WHERE table_schema = 'public'
        AND table_type = 'BASE TABLE'
      ORDER BY table_name;
    `);

    const lines = [
      '-- Auto backup generated by project backup script',
      `-- Created at: ${new Date().toISOString()}`,
      'BEGIN;',
      '',
    ];

    for (const row of tablesResult.rows) {
      const tableName = String(row.table_name);
      console.log(`Processing table: ${tableName}`);

      const columnsResult = await client.query(
        `
          SELECT column_name
          FROM information_schema.columns
          WHERE table_schema = 'public'
            AND table_name = $1
          ORDER BY ordinal_position;
        `,
        [tableName],
      );

      const columnNames = columnsResult.rows.map((col) => String(col.column_name));
      const rowsResult = await client.query(`SELECT * FROM "${tableName}"`);

      for (const currentRow of rowsResult.rows) {
        const values = columnNames.map((column) => escapedSql(currentRow[column]));
        lines.push(
          `INSERT INTO "${tableName}" (${columnNames.map((column) => `"${column}"`).join(', ')}) VALUES (${values.join(', ')});`,
        );
      }
    }

    lines.push('');
    lines.push('COMMIT;');

    const fileName = `backup_${formatStamp(new Date())}.sql`;
    const filePath = path.join(backupDir, fileName);
    fs.writeFileSync(filePath, lines.join('\n') + '\n', 'utf8');

    console.log(`Backup created successfully: ${filePath}`);
    console.log(`Tables backed up: ${tablesResult.rows.length}`);
  } finally {
    await client.end();
  }
}

main().catch((error) => {
  console.error('Backup failed:', error instanceof Error ? error.message : String(error));
  process.exit(1);
});
